name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.8.0'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Publish packages
      run: |
        for dir in packages/*; do
          if [ -d "$dir" ]; then
            DIFF_OUTPUT=$(git diff --name-only HEAD^..HEAD -- "$dir/package.json" 2>&1)
            if echo "$DIFF_OUTPUT" | grep -q "fatal"; then
              echo "$DIFF_OUTPUT"
              exit 1
            elif [ -n "$DIFF_OUTPUT" ]; then
              echo "Publishing $dir..."
              cd $dir
              echo "Checking npm authentication..."
              npm whoami
              npm publish
              cd ../..
            else
              echo "Skipping $dir..."
            fi
          fi
        done
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
